base:
    dataset_path: '../dataset/'
    y_do_one_hot_encode: True
    model_type: 'cnn_model'
    label_names:
        - '0'
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
    make_submission: True
    submission_path: '../submission/submission.csv'
# cnn model config
cnn_model:
    n_class: 10
    random_seed: 123456
    shuffle_train_data: True
    n_epoch: 5
    batch_size: 64
    save_trained_model: True
    save_trained_model_path: '../trained-model/CIFAR-10-Trained-model.h5'
    load_trained_model: True
    trained_model_path: '../trained-model/CIFAR-10-Trained-model.h5'
# knn model
